### ISSUE TITLE
Rule-based controllers

### ISSUE THREAD

**Issue by jajimer** [jajimer/energym#10]
Implementation of rule-based controllers for comparison with the DRL algorithms.

**Comment by manjavacas** [comment]
I am using `Eplus-discrete-mixed-v1` environment:

1. I was going to compare the performance of different agents vs. the rule-based driver and I have seen that the latter has stopped working. The problem comes because the parsing of variables requires `VARIABLES_FILE = 'variables.cfg'`, but now the `.cfg` file name is different.
2. I changed it to `VARIABLES_FILE = 'variablesDXVAV.cfg'` and now the problem is given by `out_temp = obs_dict['Site Outdoor Air Drybulb Temperature']`.
3. I see that the variable is now called `'Site Outdoor Air Drybulb Temperature (Environment)'`, I modify it and it manages to read it.
4. Now the problem comes in because the actions returned by the rule-based controller are tuples (e.g. `(19, 21)`), and not an integer.
 
The problem I see with this is that, unless I am missing something, there is no way to set an action "manually". We can only do it through the `_spaces.cfg` file. So, either extend the discrete action pool with those used by the rule-based controller, or add some way to enter actions manually.

On the other hand, we would also have to solve the reading of variables in `utils/controllers.py`, since the configuration file is no longer `variables.cfg` and can have any name.
